name: Deploy on Cloudflare

on:
  push:
    branches:
      - main  #replace by your branch where you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Use Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2.1.4
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
            ~/.npm
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: npm ci --prefer-offline --no-audit --no-progress

      - name: Build
        run: npm run build

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
